//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  /** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  homepage: Homepage;
  homepageConnection: HomepageConnection;
  storepage: Storepage;
  storepageConnection: StorepageConnection;
  contactpage: Contactpage;
  contactpageConnection: ContactpageConnection;
  post: Post;
  postConnection: PostConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
};


export type QueryStorepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryStorepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StorepageFilter>;
};


export type QueryContactpageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactpageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactpageFilter>;
};


export type QueryPostArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
};

export type DocumentFilter = {
  homepage?: InputMaybe<HomepageFilter>;
  storepage?: InputMaybe<StorepageFilter>;
  contactpage?: InputMaybe<ContactpageFilter>;
  post?: InputMaybe<PostFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Homepage | Storepage | Contactpage | Post | Folder;

export type HomepageHeroSlides = {
  __typename?: 'HomepageHeroSlides';
  image?: Maybe<Scalars['String']['output']>;
  mobileImage?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
};

export type HomepageAboutSection = {
  __typename?: 'HomepageAboutSection';
  eyebrow?: Maybe<Scalars['String']['output']>;
  subTitle?: Maybe<Scalars['String']['output']>;
  titleLine1?: Maybe<Scalars['String']['output']>;
  titleLine2?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  linkText?: Maybe<Scalars['String']['output']>;
};

export type HomepagePurposeSection = {
  __typename?: 'HomepagePurposeSection';
  image?: Maybe<Scalars['String']['output']>;
  visionText?: Maybe<Scalars['String']['output']>;
  missionText?: Maybe<Scalars['String']['output']>;
};

export type HomepageWhyChooseUs = {
  __typename?: 'HomepageWhyChooseUs';
  eyebrow?: Maybe<Scalars['String']['output']>;
  titleLine1?: Maybe<Scalars['String']['output']>;
  titleLine2?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type HomepageIdentityCards = {
  __typename?: 'HomepageIdentityCards';
  number?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  supportingText?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type HomepageFeatures = {
  __typename?: 'HomepageFeatures';
  number?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  iconName?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
};

export type HomepageCtaSection = {
  __typename?: 'HomepageCtaSection';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  primaryButtonText?: Maybe<Scalars['String']['output']>;
  primaryButtonUrl?: Maybe<Scalars['String']['output']>;
  secondaryButtonText?: Maybe<Scalars['String']['output']>;
  secondaryButtonUrl?: Maybe<Scalars['String']['output']>;
};

export type Homepage = Node & Document & {
  __typename?: 'Homepage';
  heroSlides?: Maybe<Array<Maybe<HomepageHeroSlides>>>;
  aboutSection?: Maybe<HomepageAboutSection>;
  purposeSection?: Maybe<HomepagePurposeSection>;
  whyChooseUs?: Maybe<HomepageWhyChooseUs>;
  identityCards?: Maybe<Array<Maybe<HomepageIdentityCards>>>;
  features?: Maybe<Array<Maybe<HomepageFeatures>>>;
  ctaSection?: Maybe<HomepageCtaSection>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomepageHeroSlidesFilter = {
  image?: InputMaybe<ImageFilter>;
  mobileImage?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
};

export type HomepageAboutSectionFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  subTitle?: InputMaybe<StringFilter>;
  titleLine1?: InputMaybe<StringFilter>;
  titleLine2?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  linkText?: InputMaybe<StringFilter>;
};

export type HomepagePurposeSectionFilter = {
  image?: InputMaybe<ImageFilter>;
  visionText?: InputMaybe<StringFilter>;
  missionText?: InputMaybe<StringFilter>;
};

export type HomepageWhyChooseUsFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  titleLine1?: InputMaybe<StringFilter>;
  titleLine2?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type HomepageIdentityCardsFilter = {
  number?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  supportingText?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type HomepageFeaturesFilter = {
  number?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  iconName?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
};

export type HomepageCtaSectionFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  primaryButtonText?: InputMaybe<StringFilter>;
  primaryButtonUrl?: InputMaybe<StringFilter>;
  secondaryButtonText?: InputMaybe<StringFilter>;
  secondaryButtonUrl?: InputMaybe<StringFilter>;
};

export type HomepageFilter = {
  heroSlides?: InputMaybe<HomepageHeroSlidesFilter>;
  aboutSection?: InputMaybe<HomepageAboutSectionFilter>;
  purposeSection?: InputMaybe<HomepagePurposeSectionFilter>;
  whyChooseUs?: InputMaybe<HomepageWhyChooseUsFilter>;
  identityCards?: InputMaybe<HomepageIdentityCardsFilter>;
  features?: InputMaybe<HomepageFeaturesFilter>;
  ctaSection?: InputMaybe<HomepageCtaSectionFilter>;
};

export type HomepageConnectionEdges = {
  __typename?: 'HomepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Homepage>;
};

export type HomepageConnection = Connection & {
  __typename?: 'HomepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageConnectionEdges>>>;
};

export type StorepageHeroSection = {
  __typename?: 'StorepageHeroSection';
  eyebrow?: Maybe<Scalars['String']['output']>;
  titleLine1?: Maybe<Scalars['String']['output']>;
  titleLine2?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  buttonText?: Maybe<Scalars['String']['output']>;
  buttonUrl?: Maybe<Scalars['String']['output']>;
  availabilityText?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
};

export type StorepageCollectionsShowcaseIntro = {
  __typename?: 'StorepageCollectionsShowcaseIntro';
  subheading?: Maybe<Scalars['String']['output']>;
  headingLine1?: Maybe<Scalars['String']['output']>;
  headingLine2?: Maybe<Scalars['String']['output']>;
  headingHighlight?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type StorepageCollectionsShowcaseCollections = {
  __typename?: 'StorepageCollectionsShowcaseCollections';
  label?: Maybe<Scalars['String']['output']>;
  heading?: Maybe<Scalars['String']['output']>;
  supportingText?: Maybe<Scalars['String']['output']>;
  ctaText?: Maybe<Scalars['String']['output']>;
  linkText?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  bgWord?: Maybe<Scalars['String']['output']>;
  layout?: Maybe<Scalars['String']['output']>;
};

export type StorepageCollectionsShowcase = {
  __typename?: 'StorepageCollectionsShowcase';
  intro?: Maybe<StorepageCollectionsShowcaseIntro>;
  collections?: Maybe<Array<Maybe<StorepageCollectionsShowcaseCollections>>>;
};

export type StorepageVisitBanner = {
  __typename?: 'StorepageVisitBanner';
  eyebrow?: Maybe<Scalars['String']['output']>;
  titleLine1?: Maybe<Scalars['String']['output']>;
  titleLine2?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  button1Text?: Maybe<Scalars['String']['output']>;
  button1Url?: Maybe<Scalars['String']['output']>;
  button2Text?: Maybe<Scalars['String']['output']>;
  button2Url?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
};

export type StorepageWhatsappCta = {
  __typename?: 'StorepageWhatsappCta';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  buttonText?: Maybe<Scalars['String']['output']>;
  noteText?: Maybe<Scalars['String']['output']>;
};

export type Storepage = Node & Document & {
  __typename?: 'Storepage';
  heroSection?: Maybe<StorepageHeroSection>;
  collectionsShowcase?: Maybe<StorepageCollectionsShowcase>;
  visitBanner?: Maybe<StorepageVisitBanner>;
  whatsappCta?: Maybe<StorepageWhatsappCta>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StorepageHeroSectionFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  titleLine1?: InputMaybe<StringFilter>;
  titleLine2?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  buttonText?: InputMaybe<StringFilter>;
  buttonUrl?: InputMaybe<StringFilter>;
  availabilityText?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
};

export type StorepageCollectionsShowcaseIntroFilter = {
  subheading?: InputMaybe<StringFilter>;
  headingLine1?: InputMaybe<StringFilter>;
  headingLine2?: InputMaybe<StringFilter>;
  headingHighlight?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type StorepageCollectionsShowcaseCollectionsFilter = {
  label?: InputMaybe<StringFilter>;
  heading?: InputMaybe<StringFilter>;
  supportingText?: InputMaybe<StringFilter>;
  ctaText?: InputMaybe<StringFilter>;
  linkText?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  bgWord?: InputMaybe<StringFilter>;
  layout?: InputMaybe<StringFilter>;
};

export type StorepageCollectionsShowcaseFilter = {
  intro?: InputMaybe<StorepageCollectionsShowcaseIntroFilter>;
  collections?: InputMaybe<StorepageCollectionsShowcaseCollectionsFilter>;
};

export type StorepageVisitBannerFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  titleLine1?: InputMaybe<StringFilter>;
  titleLine2?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  button1Text?: InputMaybe<StringFilter>;
  button1Url?: InputMaybe<StringFilter>;
  button2Text?: InputMaybe<StringFilter>;
  button2Url?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
};

export type StorepageWhatsappCtaFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  buttonText?: InputMaybe<StringFilter>;
  noteText?: InputMaybe<StringFilter>;
};

export type StorepageFilter = {
  heroSection?: InputMaybe<StorepageHeroSectionFilter>;
  collectionsShowcase?: InputMaybe<StorepageCollectionsShowcaseFilter>;
  visitBanner?: InputMaybe<StorepageVisitBannerFilter>;
  whatsappCta?: InputMaybe<StorepageWhatsappCtaFilter>;
};

export type StorepageConnectionEdges = {
  __typename?: 'StorepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Storepage>;
};

export type StorepageConnection = Connection & {
  __typename?: 'StorepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<StorepageConnectionEdges>>>;
};

export type ContactpageHeroSection = {
  __typename?: 'ContactpageHeroSection';
  eyebrow?: Maybe<Scalars['String']['output']>;
  titleLine1?: Maybe<Scalars['String']['output']>;
  titleLine2?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  button1Text?: Maybe<Scalars['String']['output']>;
  button1Url?: Maybe<Scalars['String']['output']>;
  button2Text?: Maybe<Scalars['String']['output']>;
  button2Url?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
};

export type ContactpageContactCards = {
  __typename?: 'ContactpageContactCards';
  iconName?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  info?: Maybe<Scalars['String']['output']>;
  actionText?: Maybe<Scalars['String']['output']>;
  link?: Maybe<Scalars['String']['output']>;
};

export type ContactpageReachUsSectionMethods = {
  __typename?: 'ContactpageReachUsSectionMethods';
  iconName?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  primaryText?: Maybe<Scalars['String']['output']>;
  primaryLink?: Maybe<Scalars['String']['output']>;
  secondaryText?: Maybe<Scalars['String']['output']>;
  secondaryLink?: Maybe<Scalars['String']['output']>;
};

export type ContactpageReachUsSection = {
  __typename?: 'ContactpageReachUsSection';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  methods?: Maybe<Array<Maybe<ContactpageReachUsSectionMethods>>>;
};

export type ContactpageFormSection = {
  __typename?: 'ContactpageFormSection';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  formspreeUrl?: Maybe<Scalars['String']['output']>;
  buttonText?: Maybe<Scalars['String']['output']>;
};

export type ContactpageWhatsappBanner = {
  __typename?: 'ContactpageWhatsappBanner';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  buttonText?: Maybe<Scalars['String']['output']>;
  buttonUrl?: Maybe<Scalars['String']['output']>;
};

export type ContactpageFaqSectionFaqs = {
  __typename?: 'ContactpageFaqSectionFaqs';
  question?: Maybe<Scalars['String']['output']>;
  answer?: Maybe<Scalars['String']['output']>;
};

export type ContactpageFaqSection = {
  __typename?: 'ContactpageFaqSection';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  faqs?: Maybe<Array<Maybe<ContactpageFaqSectionFaqs>>>;
};

export type Contactpage = Node & Document & {
  __typename?: 'Contactpage';
  heroSection?: Maybe<ContactpageHeroSection>;
  contactCards?: Maybe<Array<Maybe<ContactpageContactCards>>>;
  reachUsSection?: Maybe<ContactpageReachUsSection>;
  formSection?: Maybe<ContactpageFormSection>;
  whatsappBanner?: Maybe<ContactpageWhatsappBanner>;
  faqSection?: Maybe<ContactpageFaqSection>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactpageHeroSectionFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  titleLine1?: InputMaybe<StringFilter>;
  titleLine2?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  button1Text?: InputMaybe<StringFilter>;
  button1Url?: InputMaybe<StringFilter>;
  button2Text?: InputMaybe<StringFilter>;
  button2Url?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
};

export type ContactpageContactCardsFilter = {
  iconName?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  info?: InputMaybe<StringFilter>;
  actionText?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
};

export type ContactpageReachUsSectionMethodsFilter = {
  iconName?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  primaryText?: InputMaybe<StringFilter>;
  primaryLink?: InputMaybe<StringFilter>;
  secondaryText?: InputMaybe<StringFilter>;
  secondaryLink?: InputMaybe<StringFilter>;
};

export type ContactpageReachUsSectionFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  methods?: InputMaybe<ContactpageReachUsSectionMethodsFilter>;
};

export type ContactpageFormSectionFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  formspreeUrl?: InputMaybe<StringFilter>;
  buttonText?: InputMaybe<StringFilter>;
};

export type ContactpageWhatsappBannerFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  buttonText?: InputMaybe<StringFilter>;
  buttonUrl?: InputMaybe<StringFilter>;
};

export type ContactpageFaqSectionFaqsFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type ContactpageFaqSectionFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  faqs?: InputMaybe<ContactpageFaqSectionFaqsFilter>;
};

export type ContactpageFilter = {
  heroSection?: InputMaybe<ContactpageHeroSectionFilter>;
  contactCards?: InputMaybe<ContactpageContactCardsFilter>;
  reachUsSection?: InputMaybe<ContactpageReachUsSectionFilter>;
  formSection?: InputMaybe<ContactpageFormSectionFilter>;
  whatsappBanner?: InputMaybe<ContactpageWhatsappBannerFilter>;
  faqSection?: InputMaybe<ContactpageFaqSectionFilter>;
};

export type ContactpageConnectionEdges = {
  __typename?: 'ContactpageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contactpage>;
};

export type ContactpageConnection = Connection & {
  __typename?: 'ContactpageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactpageConnectionEdges>>>;
};

export type Post = Node & Document & {
  __typename?: 'Post';
  title: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PostFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PostConnectionEdges = {
  __typename?: 'PostConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Post>;
};

export type PostConnection = Connection & {
  __typename?: 'PostConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PostConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHomepage: Homepage;
  createHomepage: Homepage;
  updateStorepage: Storepage;
  createStorepage: Storepage;
  updateContactpage: Contactpage;
  createContactpage: Contactpage;
  updatePost: Post;
  createPost: Post;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationCreateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationUpdateStorepageArgs = {
  relativePath: Scalars['String']['input'];
  params: StorepageMutation;
};


export type MutationCreateStorepageArgs = {
  relativePath: Scalars['String']['input'];
  params: StorepageMutation;
};


export type MutationUpdateContactpageArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactpageMutation;
};


export type MutationCreateContactpageArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactpageMutation;
};


export type MutationUpdatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};


export type MutationCreatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};

export type DocumentUpdateMutation = {
  homepage?: InputMaybe<HomepageMutation>;
  storepage?: InputMaybe<StorepageMutation>;
  contactpage?: InputMaybe<ContactpageMutation>;
  post?: InputMaybe<PostMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  homepage?: InputMaybe<HomepageMutation>;
  storepage?: InputMaybe<StorepageMutation>;
  contactpage?: InputMaybe<ContactpageMutation>;
  post?: InputMaybe<PostMutation>;
};

export type HomepageHeroSlidesMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  mobileImage?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageAboutSectionMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  subTitle?: InputMaybe<Scalars['String']['input']>;
  titleLine1?: InputMaybe<Scalars['String']['input']>;
  titleLine2?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  linkText?: InputMaybe<Scalars['String']['input']>;
};

export type HomepagePurposeSectionMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  visionText?: InputMaybe<Scalars['String']['input']>;
  missionText?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageWhyChooseUsMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  titleLine1?: InputMaybe<Scalars['String']['input']>;
  titleLine2?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageIdentityCardsMutation = {
  number?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  supportingText?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageFeaturesMutation = {
  number?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  iconName?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageCtaSectionMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  primaryButtonText?: InputMaybe<Scalars['String']['input']>;
  primaryButtonUrl?: InputMaybe<Scalars['String']['input']>;
  secondaryButtonText?: InputMaybe<Scalars['String']['input']>;
  secondaryButtonUrl?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageMutation = {
  heroSlides?: InputMaybe<Array<InputMaybe<HomepageHeroSlidesMutation>>>;
  aboutSection?: InputMaybe<HomepageAboutSectionMutation>;
  purposeSection?: InputMaybe<HomepagePurposeSectionMutation>;
  whyChooseUs?: InputMaybe<HomepageWhyChooseUsMutation>;
  identityCards?: InputMaybe<Array<InputMaybe<HomepageIdentityCardsMutation>>>;
  features?: InputMaybe<Array<InputMaybe<HomepageFeaturesMutation>>>;
  ctaSection?: InputMaybe<HomepageCtaSectionMutation>;
};

export type StorepageHeroSectionMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  titleLine1?: InputMaybe<Scalars['String']['input']>;
  titleLine2?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  buttonText?: InputMaybe<Scalars['String']['input']>;
  buttonUrl?: InputMaybe<Scalars['String']['input']>;
  availabilityText?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
};

export type StorepageCollectionsShowcaseIntroMutation = {
  subheading?: InputMaybe<Scalars['String']['input']>;
  headingLine1?: InputMaybe<Scalars['String']['input']>;
  headingLine2?: InputMaybe<Scalars['String']['input']>;
  headingHighlight?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type StorepageCollectionsShowcaseCollectionsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  heading?: InputMaybe<Scalars['String']['input']>;
  supportingText?: InputMaybe<Scalars['String']['input']>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
  linkText?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  bgWord?: InputMaybe<Scalars['String']['input']>;
  layout?: InputMaybe<Scalars['String']['input']>;
};

export type StorepageCollectionsShowcaseMutation = {
  intro?: InputMaybe<StorepageCollectionsShowcaseIntroMutation>;
  collections?: InputMaybe<Array<InputMaybe<StorepageCollectionsShowcaseCollectionsMutation>>>;
};

export type StorepageVisitBannerMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  titleLine1?: InputMaybe<Scalars['String']['input']>;
  titleLine2?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  button1Text?: InputMaybe<Scalars['String']['input']>;
  button1Url?: InputMaybe<Scalars['String']['input']>;
  button2Text?: InputMaybe<Scalars['String']['input']>;
  button2Url?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
};

export type StorepageWhatsappCtaMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  buttonText?: InputMaybe<Scalars['String']['input']>;
  noteText?: InputMaybe<Scalars['String']['input']>;
};

export type StorepageMutation = {
  heroSection?: InputMaybe<StorepageHeroSectionMutation>;
  collectionsShowcase?: InputMaybe<StorepageCollectionsShowcaseMutation>;
  visitBanner?: InputMaybe<StorepageVisitBannerMutation>;
  whatsappCta?: InputMaybe<StorepageWhatsappCtaMutation>;
};

export type ContactpageHeroSectionMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  titleLine1?: InputMaybe<Scalars['String']['input']>;
  titleLine2?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  button1Text?: InputMaybe<Scalars['String']['input']>;
  button1Url?: InputMaybe<Scalars['String']['input']>;
  button2Text?: InputMaybe<Scalars['String']['input']>;
  button2Url?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
};

export type ContactpageContactCardsMutation = {
  iconName?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  info?: InputMaybe<Scalars['String']['input']>;
  actionText?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
};

export type ContactpageReachUsSectionMethodsMutation = {
  iconName?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  primaryText?: InputMaybe<Scalars['String']['input']>;
  primaryLink?: InputMaybe<Scalars['String']['input']>;
  secondaryText?: InputMaybe<Scalars['String']['input']>;
  secondaryLink?: InputMaybe<Scalars['String']['input']>;
};

export type ContactpageReachUsSectionMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  methods?: InputMaybe<Array<InputMaybe<ContactpageReachUsSectionMethodsMutation>>>;
};

export type ContactpageFormSectionMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  formspreeUrl?: InputMaybe<Scalars['String']['input']>;
  buttonText?: InputMaybe<Scalars['String']['input']>;
};

export type ContactpageWhatsappBannerMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  buttonText?: InputMaybe<Scalars['String']['input']>;
  buttonUrl?: InputMaybe<Scalars['String']['input']>;
};

export type ContactpageFaqSectionFaqsMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type ContactpageFaqSectionMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  faqs?: InputMaybe<Array<InputMaybe<ContactpageFaqSectionFaqsMutation>>>;
};

export type ContactpageMutation = {
  heroSection?: InputMaybe<ContactpageHeroSectionMutation>;
  contactCards?: InputMaybe<Array<InputMaybe<ContactpageContactCardsMutation>>>;
  reachUsSection?: InputMaybe<ContactpageReachUsSectionMutation>;
  formSection?: InputMaybe<ContactpageFormSectionMutation>;
  whatsappBanner?: InputMaybe<ContactpageWhatsappBannerMutation>;
  faqSection?: InputMaybe<ContactpageFaqSectionMutation>;
};

export type PostMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type HomepageHeroSlidesFilter = {
  image?: ImageFilter | null | undefined;
  mobileImage?: ImageFilter | null | undefined;
  imageAlt?: StringFilter | null | undefined;
};

export type HomepageAboutSectionFilter = {
  eyebrow?: StringFilter | null | undefined;
  subTitle?: StringFilter | null | undefined;
  titleLine1?: StringFilter | null | undefined;
  titleLine2?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  linkText?: StringFilter | null | undefined;
};

export type HomepagePurposeSectionFilter = {
  image?: ImageFilter | null | undefined;
  visionText?: StringFilter | null | undefined;
  missionText?: StringFilter | null | undefined;
};

export type HomepageWhyChooseUsFilter = {
  eyebrow?: StringFilter | null | undefined;
  titleLine1?: StringFilter | null | undefined;
  titleLine2?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
};

export type HomepageIdentityCardsFilter = {
  number?: StringFilter | null | undefined;
  label?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  supportingText?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  imageAlt?: StringFilter | null | undefined;
  href?: StringFilter | null | undefined;
};

export type HomepageFeaturesFilter = {
  number?: StringFilter | null | undefined;
  label?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  iconName?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  imageAlt?: StringFilter | null | undefined;
};

export type HomepageCtaSectionFilter = {
  eyebrow?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  primaryButtonText?: StringFilter | null | undefined;
  primaryButtonUrl?: StringFilter | null | undefined;
  secondaryButtonText?: StringFilter | null | undefined;
  secondaryButtonUrl?: StringFilter | null | undefined;
};

export type HomepageFilter = {
  heroSlides?: HomepageHeroSlidesFilter | null | undefined;
  aboutSection?: HomepageAboutSectionFilter | null | undefined;
  purposeSection?: HomepagePurposeSectionFilter | null | undefined;
  whyChooseUs?: HomepageWhyChooseUsFilter | null | undefined;
  identityCards?: HomepageIdentityCardsFilter | null | undefined;
  features?: HomepageFeaturesFilter | null | undefined;
  ctaSection?: HomepageCtaSectionFilter | null | undefined;
};

export type StorepageHeroSectionFilter = {
  eyebrow?: StringFilter | null | undefined;
  titleLine1?: StringFilter | null | undefined;
  titleLine2?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  buttonText?: StringFilter | null | undefined;
  buttonUrl?: StringFilter | null | undefined;
  availabilityText?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  imageAlt?: StringFilter | null | undefined;
};

export type StorepageCollectionsShowcaseIntroFilter = {
  subheading?: StringFilter | null | undefined;
  headingLine1?: StringFilter | null | undefined;
  headingLine2?: StringFilter | null | undefined;
  headingHighlight?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
};

export type StorepageCollectionsShowcaseCollectionsFilter = {
  label?: StringFilter | null | undefined;
  heading?: StringFilter | null | undefined;
  supportingText?: StringFilter | null | undefined;
  ctaText?: StringFilter | null | undefined;
  linkText?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  imageAlt?: StringFilter | null | undefined;
  bgWord?: StringFilter | null | undefined;
  layout?: StringFilter | null | undefined;
};

export type StorepageCollectionsShowcaseFilter = {
  intro?: StorepageCollectionsShowcaseIntroFilter | null | undefined;
  collections?: StorepageCollectionsShowcaseCollectionsFilter | null | undefined;
};

export type StorepageVisitBannerFilter = {
  eyebrow?: StringFilter | null | undefined;
  titleLine1?: StringFilter | null | undefined;
  titleLine2?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  button1Text?: StringFilter | null | undefined;
  button1Url?: StringFilter | null | undefined;
  button2Text?: StringFilter | null | undefined;
  button2Url?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  imageAlt?: StringFilter | null | undefined;
};

export type StorepageWhatsappCtaFilter = {
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  buttonText?: StringFilter | null | undefined;
  noteText?: StringFilter | null | undefined;
};

export type StorepageFilter = {
  heroSection?: StorepageHeroSectionFilter | null | undefined;
  collectionsShowcase?: StorepageCollectionsShowcaseFilter | null | undefined;
  visitBanner?: StorepageVisitBannerFilter | null | undefined;
  whatsappCta?: StorepageWhatsappCtaFilter | null | undefined;
};

export type ContactpageHeroSectionFilter = {
  eyebrow?: StringFilter | null | undefined;
  titleLine1?: StringFilter | null | undefined;
  titleLine2?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  button1Text?: StringFilter | null | undefined;
  button1Url?: StringFilter | null | undefined;
  button2Text?: StringFilter | null | undefined;
  button2Url?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  imageAlt?: StringFilter | null | undefined;
};

export type ContactpageContactCardsFilter = {
  iconName?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  info?: StringFilter | null | undefined;
  actionText?: StringFilter | null | undefined;
  link?: StringFilter | null | undefined;
};

export type ContactpageReachUsSectionMethodsFilter = {
  iconName?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  primaryText?: StringFilter | null | undefined;
  primaryLink?: StringFilter | null | undefined;
  secondaryText?: StringFilter | null | undefined;
  secondaryLink?: StringFilter | null | undefined;
};

export type ContactpageReachUsSectionFilter = {
  eyebrow?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  methods?: ContactpageReachUsSectionMethodsFilter | null | undefined;
};

export type ContactpageFormSectionFilter = {
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  formspreeUrl?: StringFilter | null | undefined;
  buttonText?: StringFilter | null | undefined;
};

export type ContactpageWhatsappBannerFilter = {
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  buttonText?: StringFilter | null | undefined;
  buttonUrl?: StringFilter | null | undefined;
};

export type ContactpageFaqSectionFaqsFilter = {
  question?: StringFilter | null | undefined;
  answer?: StringFilter | null | undefined;
};

export type ContactpageFaqSectionFilter = {
  eyebrow?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  faqs?: ContactpageFaqSectionFaqsFilter | null | undefined;
};

export type ContactpageFilter = {
  heroSection?: ContactpageHeroSectionFilter | null | undefined;
  contactCards?: ContactpageContactCardsFilter | null | undefined;
  reachUsSection?: ContactpageReachUsSectionFilter | null | undefined;
  formSection?: ContactpageFormSectionFilter | null | undefined;
  whatsappBanner?: ContactpageWhatsappBannerFilter | null | undefined;
  faqSection?: ContactpageFaqSectionFilter | null | undefined;
};

export type RichTextFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
};

export type PostFilter = {
  title?: StringFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type HomepagePartsFragment = { __typename: 'Homepage', heroSlides: Array<{ __typename: 'HomepageHeroSlides', image: string | null, mobileImage: string | null, imageAlt: string | null } | null> | null, aboutSection: { __typename: 'HomepageAboutSection', eyebrow: string | null, subTitle: string | null, titleLine1: string | null, titleLine2: string | null, description: string | null, linkText: string | null } | null, purposeSection: { __typename: 'HomepagePurposeSection', image: string | null, visionText: string | null, missionText: string | null } | null, whyChooseUs: { __typename: 'HomepageWhyChooseUs', eyebrow: string | null, titleLine1: string | null, titleLine2: string | null, description: string | null } | null, identityCards: Array<{ __typename: 'HomepageIdentityCards', number: string | null, label: string | null, title: string | null, description: string | null, supportingText: string | null, image: string | null, imageAlt: string | null, href: string | null } | null> | null, features: Array<{ __typename: 'HomepageFeatures', number: string | null, label: string | null, title: string | null, description: string | null, iconName: string | null, image: string | null, imageAlt: string | null } | null> | null, ctaSection: { __typename: 'HomepageCtaSection', eyebrow: string | null, title: string | null, description: string | null, primaryButtonText: string | null, primaryButtonUrl: string | null, secondaryButtonText: string | null, secondaryButtonUrl: string | null } | null };

export type StorepagePartsFragment = { __typename: 'Storepage', heroSection: { __typename: 'StorepageHeroSection', eyebrow: string | null, titleLine1: string | null, titleLine2: string | null, description: string | null, buttonText: string | null, buttonUrl: string | null, availabilityText: string | null, image: string | null, imageAlt: string | null } | null, collectionsShowcase: { __typename: 'StorepageCollectionsShowcase', intro: { __typename: 'StorepageCollectionsShowcaseIntro', subheading: string | null, headingLine1: string | null, headingLine2: string | null, headingHighlight: string | null, description: string | null } | null, collections: Array<{ __typename: 'StorepageCollectionsShowcaseCollections', label: string | null, heading: string | null, supportingText: string | null, ctaText: string | null, linkText: string | null, image: string | null, imageAlt: string | null, bgWord: string | null, layout: string | null } | null> | null } | null, visitBanner: { __typename: 'StorepageVisitBanner', eyebrow: string | null, titleLine1: string | null, titleLine2: string | null, description: string | null, button1Text: string | null, button1Url: string | null, button2Text: string | null, button2Url: string | null, image: string | null, imageAlt: string | null } | null, whatsappCta: { __typename: 'StorepageWhatsappCta', title: string | null, description: string | null, buttonText: string | null, noteText: string | null } | null };

export type ContactpagePartsFragment = { __typename: 'Contactpage', heroSection: { __typename: 'ContactpageHeroSection', eyebrow: string | null, titleLine1: string | null, titleLine2: string | null, description: string | null, button1Text: string | null, button1Url: string | null, button2Text: string | null, button2Url: string | null, image: string | null, imageAlt: string | null } | null, contactCards: Array<{ __typename: 'ContactpageContactCards', iconName: string | null, title: string | null, description: string | null, info: string | null, actionText: string | null, link: string | null } | null> | null, reachUsSection: { __typename: 'ContactpageReachUsSection', eyebrow: string | null, title: string | null, methods: Array<{ __typename: 'ContactpageReachUsSectionMethods', iconName: string | null, title: string | null, description: string | null, primaryText: string | null, primaryLink: string | null, secondaryText: string | null, secondaryLink: string | null } | null> | null } | null, formSection: { __typename: 'ContactpageFormSection', title: string | null, description: string | null, formspreeUrl: string | null, buttonText: string | null } | null, whatsappBanner: { __typename: 'ContactpageWhatsappBanner', title: string | null, description: string | null, buttonText: string | null, buttonUrl: string | null } | null, faqSection: { __typename: 'ContactpageFaqSection', eyebrow: string | null, title: string | null, faqs: Array<{ __typename: 'ContactpageFaqSectionFaqs', question: string | null, answer: string | null } | null> | null } | null };

export type PostPartsFragment = { __typename: 'Post', title: string, body: any };

export type HomepageQueryVariables = Exact<{
  relativePath: string;
}>;


export type HomepageQuery = { homepage: { __typename: 'Homepage', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, heroSlides: Array<{ __typename: 'HomepageHeroSlides', image: string | null, mobileImage: string | null, imageAlt: string | null } | null> | null, aboutSection: { __typename: 'HomepageAboutSection', eyebrow: string | null, subTitle: string | null, titleLine1: string | null, titleLine2: string | null, description: string | null, linkText: string | null } | null, purposeSection: { __typename: 'HomepagePurposeSection', image: string | null, visionText: string | null, missionText: string | null } | null, whyChooseUs: { __typename: 'HomepageWhyChooseUs', eyebrow: string | null, titleLine1: string | null, titleLine2: string | null, description: string | null } | null, identityCards: Array<{ __typename: 'HomepageIdentityCards', number: string | null, label: string | null, title: string | null, description: string | null, supportingText: string | null, image: string | null, imageAlt: string | null, href: string | null } | null> | null, features: Array<{ __typename: 'HomepageFeatures', number: string | null, label: string | null, title: string | null, description: string | null, iconName: string | null, image: string | null, imageAlt: string | null } | null> | null, ctaSection: { __typename: 'HomepageCtaSection', eyebrow: string | null, title: string | null, description: string | null, primaryButtonText: string | null, primaryButtonUrl: string | null, secondaryButtonText: string | null, secondaryButtonUrl: string | null } | null } };

export type HomepageConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: HomepageFilter | null | undefined;
}>;


export type HomepageConnectionQuery = { homepageConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Homepage', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, heroSlides: Array<{ __typename: 'HomepageHeroSlides', image: string | null, mobileImage: string | null, imageAlt: string | null } | null> | null, aboutSection: { __typename: 'HomepageAboutSection', eyebrow: string | null, subTitle: string | null, titleLine1: string | null, titleLine2: string | null, description: string | null, linkText: string | null } | null, purposeSection: { __typename: 'HomepagePurposeSection', image: string | null, visionText: string | null, missionText: string | null } | null, whyChooseUs: { __typename: 'HomepageWhyChooseUs', eyebrow: string | null, titleLine1: string | null, titleLine2: string | null, description: string | null } | null, identityCards: Array<{ __typename: 'HomepageIdentityCards', number: string | null, label: string | null, title: string | null, description: string | null, supportingText: string | null, image: string | null, imageAlt: string | null, href: string | null } | null> | null, features: Array<{ __typename: 'HomepageFeatures', number: string | null, label: string | null, title: string | null, description: string | null, iconName: string | null, image: string | null, imageAlt: string | null } | null> | null, ctaSection: { __typename: 'HomepageCtaSection', eyebrow: string | null, title: string | null, description: string | null, primaryButtonText: string | null, primaryButtonUrl: string | null, secondaryButtonText: string | null, secondaryButtonUrl: string | null } | null } | null } | null> | null } };

export type StorepageQueryVariables = Exact<{
  relativePath: string;
}>;


export type StorepageQuery = { storepage: { __typename: 'Storepage', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, heroSection: { __typename: 'StorepageHeroSection', eyebrow: string | null, titleLine1: string | null, titleLine2: string | null, description: string | null, buttonText: string | null, buttonUrl: string | null, availabilityText: string | null, image: string | null, imageAlt: string | null } | null, collectionsShowcase: { __typename: 'StorepageCollectionsShowcase', intro: { __typename: 'StorepageCollectionsShowcaseIntro', subheading: string | null, headingLine1: string | null, headingLine2: string | null, headingHighlight: string | null, description: string | null } | null, collections: Array<{ __typename: 'StorepageCollectionsShowcaseCollections', label: string | null, heading: string | null, supportingText: string | null, ctaText: string | null, linkText: string | null, image: string | null, imageAlt: string | null, bgWord: string | null, layout: string | null } | null> | null } | null, visitBanner: { __typename: 'StorepageVisitBanner', eyebrow: string | null, titleLine1: string | null, titleLine2: string | null, description: string | null, button1Text: string | null, button1Url: string | null, button2Text: string | null, button2Url: string | null, image: string | null, imageAlt: string | null } | null, whatsappCta: { __typename: 'StorepageWhatsappCta', title: string | null, description: string | null, buttonText: string | null, noteText: string | null } | null } };

export type StorepageConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: StorepageFilter | null | undefined;
}>;


export type StorepageConnectionQuery = { storepageConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Storepage', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, heroSection: { __typename: 'StorepageHeroSection', eyebrow: string | null, titleLine1: string | null, titleLine2: string | null, description: string | null, buttonText: string | null, buttonUrl: string | null, availabilityText: string | null, image: string | null, imageAlt: string | null } | null, collectionsShowcase: { __typename: 'StorepageCollectionsShowcase', intro: { __typename: 'StorepageCollectionsShowcaseIntro', subheading: string | null, headingLine1: string | null, headingLine2: string | null, headingHighlight: string | null, description: string | null } | null, collections: Array<{ __typename: 'StorepageCollectionsShowcaseCollections', label: string | null, heading: string | null, supportingText: string | null, ctaText: string | null, linkText: string | null, image: string | null, imageAlt: string | null, bgWord: string | null, layout: string | null } | null> | null } | null, visitBanner: { __typename: 'StorepageVisitBanner', eyebrow: string | null, titleLine1: string | null, titleLine2: string | null, description: string | null, button1Text: string | null, button1Url: string | null, button2Text: string | null, button2Url: string | null, image: string | null, imageAlt: string | null } | null, whatsappCta: { __typename: 'StorepageWhatsappCta', title: string | null, description: string | null, buttonText: string | null, noteText: string | null } | null } | null } | null> | null } };

export type ContactpageQueryVariables = Exact<{
  relativePath: string;
}>;


export type ContactpageQuery = { contactpage: { __typename: 'Contactpage', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, heroSection: { __typename: 'ContactpageHeroSection', eyebrow: string | null, titleLine1: string | null, titleLine2: string | null, description: string | null, button1Text: string | null, button1Url: string | null, button2Text: string | null, button2Url: string | null, image: string | null, imageAlt: string | null } | null, contactCards: Array<{ __typename: 'ContactpageContactCards', iconName: string | null, title: string | null, description: string | null, info: string | null, actionText: string | null, link: string | null } | null> | null, reachUsSection: { __typename: 'ContactpageReachUsSection', eyebrow: string | null, title: string | null, methods: Array<{ __typename: 'ContactpageReachUsSectionMethods', iconName: string | null, title: string | null, description: string | null, primaryText: string | null, primaryLink: string | null, secondaryText: string | null, secondaryLink: string | null } | null> | null } | null, formSection: { __typename: 'ContactpageFormSection', title: string | null, description: string | null, formspreeUrl: string | null, buttonText: string | null } | null, whatsappBanner: { __typename: 'ContactpageWhatsappBanner', title: string | null, description: string | null, buttonText: string | null, buttonUrl: string | null } | null, faqSection: { __typename: 'ContactpageFaqSection', eyebrow: string | null, title: string | null, faqs: Array<{ __typename: 'ContactpageFaqSectionFaqs', question: string | null, answer: string | null } | null> | null } | null } };

export type ContactpageConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: ContactpageFilter | null | undefined;
}>;


export type ContactpageConnectionQuery = { contactpageConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Contactpage', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, heroSection: { __typename: 'ContactpageHeroSection', eyebrow: string | null, titleLine1: string | null, titleLine2: string | null, description: string | null, button1Text: string | null, button1Url: string | null, button2Text: string | null, button2Url: string | null, image: string | null, imageAlt: string | null } | null, contactCards: Array<{ __typename: 'ContactpageContactCards', iconName: string | null, title: string | null, description: string | null, info: string | null, actionText: string | null, link: string | null } | null> | null, reachUsSection: { __typename: 'ContactpageReachUsSection', eyebrow: string | null, title: string | null, methods: Array<{ __typename: 'ContactpageReachUsSectionMethods', iconName: string | null, title: string | null, description: string | null, primaryText: string | null, primaryLink: string | null, secondaryText: string | null, secondaryLink: string | null } | null> | null } | null, formSection: { __typename: 'ContactpageFormSection', title: string | null, description: string | null, formspreeUrl: string | null, buttonText: string | null } | null, whatsappBanner: { __typename: 'ContactpageWhatsappBanner', title: string | null, description: string | null, buttonText: string | null, buttonUrl: string | null } | null, faqSection: { __typename: 'ContactpageFaqSection', eyebrow: string | null, title: string | null, faqs: Array<{ __typename: 'ContactpageFaqSectionFaqs', question: string | null, answer: string | null } | null> | null } | null } | null } | null> | null } };

export type PostQueryVariables = Exact<{
  relativePath: string;
}>;


export type PostQuery = { post: { __typename: 'Post', id: string, title: string, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PostConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PostFilter | null | undefined;
}>;


export type PostConnectionQuery = { postConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Post', id: string, title: string, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const HomepagePartsFragmentDoc = gql`
    fragment HomepageParts on Homepage {
  __typename
  heroSlides {
    __typename
    image
    mobileImage
    imageAlt
  }
  aboutSection {
    __typename
    eyebrow
    subTitle
    titleLine1
    titleLine2
    description
    linkText
  }
  purposeSection {
    __typename
    image
    visionText
    missionText
  }
  whyChooseUs {
    __typename
    eyebrow
    titleLine1
    titleLine2
    description
  }
  identityCards {
    __typename
    number
    label
    title
    description
    supportingText
    image
    imageAlt
    href
  }
  features {
    __typename
    number
    label
    title
    description
    iconName
    image
    imageAlt
  }
  ctaSection {
    __typename
    eyebrow
    title
    description
    primaryButtonText
    primaryButtonUrl
    secondaryButtonText
    secondaryButtonUrl
  }
}
    `;
export const StorepagePartsFragmentDoc = gql`
    fragment StorepageParts on Storepage {
  __typename
  heroSection {
    __typename
    eyebrow
    titleLine1
    titleLine2
    description
    buttonText
    buttonUrl
    availabilityText
    image
    imageAlt
  }
  collectionsShowcase {
    __typename
    intro {
      __typename
      subheading
      headingLine1
      headingLine2
      headingHighlight
      description
    }
    collections {
      __typename
      label
      heading
      supportingText
      ctaText
      linkText
      image
      imageAlt
      bgWord
      layout
    }
  }
  visitBanner {
    __typename
    eyebrow
    titleLine1
    titleLine2
    description
    button1Text
    button1Url
    button2Text
    button2Url
    image
    imageAlt
  }
  whatsappCta {
    __typename
    title
    description
    buttonText
    noteText
  }
}
    `;
export const ContactpagePartsFragmentDoc = gql`
    fragment ContactpageParts on Contactpage {
  __typename
  heroSection {
    __typename
    eyebrow
    titleLine1
    titleLine2
    description
    button1Text
    button1Url
    button2Text
    button2Url
    image
    imageAlt
  }
  contactCards {
    __typename
    iconName
    title
    description
    info
    actionText
    link
  }
  reachUsSection {
    __typename
    eyebrow
    title
    methods {
      __typename
      iconName
      title
      description
      primaryText
      primaryLink
      secondaryText
      secondaryLink
    }
  }
  formSection {
    __typename
    title
    description
    formspreeUrl
    buttonText
  }
  whatsappBanner {
    __typename
    title
    description
    buttonText
    buttonUrl
  }
  faqSection {
    __typename
    eyebrow
    title
    faqs {
      __typename
      question
      answer
    }
  }
}
    `;
export const PostPartsFragmentDoc = gql`
    fragment PostParts on Post {
  __typename
  title
  body
}
    `;
export const HomepageDocument = gql`
    query homepage($relativePath: String!) {
  homepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageParts
  }
}
    ${HomepagePartsFragmentDoc}`;
export const HomepageConnectionDocument = gql`
    query homepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFilter) {
  homepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageParts
      }
    }
  }
}
    ${HomepagePartsFragmentDoc}`;
export const StorepageDocument = gql`
    query storepage($relativePath: String!) {
  storepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...StorepageParts
  }
}
    ${StorepagePartsFragmentDoc}`;
export const StorepageConnectionDocument = gql`
    query storepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: StorepageFilter) {
  storepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...StorepageParts
      }
    }
  }
}
    ${StorepagePartsFragmentDoc}`;
export const ContactpageDocument = gql`
    query contactpage($relativePath: String!) {
  contactpage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactpageParts
  }
}
    ${ContactpagePartsFragmentDoc}`;
export const ContactpageConnectionDocument = gql`
    query contactpageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactpageFilter) {
  contactpageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactpageParts
      }
    }
  }
}
    ${ContactpagePartsFragmentDoc}`;
export const PostDocument = gql`
    query post($relativePath: String!) {
  post(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PostParts
  }
}
    ${PostPartsFragmentDoc}`;
export const PostConnectionDocument = gql`
    query postConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PostFilter) {
  postConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PostParts
      }
    }
  }
}
    ${PostPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      homepage(variables: HomepageQueryVariables, options?: C): Promise<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}> {
        return requester<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}, HomepageQueryVariables>(HomepageDocument, variables, options);
      },
    homepageConnection(variables?: HomepageConnectionQueryVariables, options?: C): Promise<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}, HomepageConnectionQueryVariables>(HomepageConnectionDocument, variables, options);
      },
    storepage(variables: StorepageQueryVariables, options?: C): Promise<{data: StorepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StorepageQueryVariables, query: string}> {
        return requester<{data: StorepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StorepageQueryVariables, query: string}, StorepageQueryVariables>(StorepageDocument, variables, options);
      },
    storepageConnection(variables?: StorepageConnectionQueryVariables, options?: C): Promise<{data: StorepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StorepageConnectionQueryVariables, query: string}> {
        return requester<{data: StorepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StorepageConnectionQueryVariables, query: string}, StorepageConnectionQueryVariables>(StorepageConnectionDocument, variables, options);
      },
    contactpage(variables: ContactpageQueryVariables, options?: C): Promise<{data: ContactpageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactpageQueryVariables, query: string}> {
        return requester<{data: ContactpageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactpageQueryVariables, query: string}, ContactpageQueryVariables>(ContactpageDocument, variables, options);
      },
    contactpageConnection(variables?: ContactpageConnectionQueryVariables, options?: C): Promise<{data: ContactpageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactpageConnectionQueryVariables, query: string}> {
        return requester<{data: ContactpageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactpageConnectionQueryVariables, query: string}, ContactpageConnectionQueryVariables>(ContactpageConnectionDocument, variables, options);
      },
    post(variables: PostQueryVariables, options?: C): Promise<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}> {
        return requester<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}, PostQueryVariables>(PostDocument, variables, options);
      },
    postConnection(variables?: PostConnectionQueryVariables, options?: C): Promise<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}> {
        return requester<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}, PostConnectionQueryVariables>(PostConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  